TunerMovie/TunerMovie/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TunerMovie.Models;

namespace TunerMovie.Controllers
{
    public class MovieController : Controller
    {
        //TitlesEntitiesNew _db;
        TitlesEntities _db;
        public MovieController()
        {
            //_db = new TitlesEntitiesNew();
            _db = new TitlesEntities();
        }

        public ActionResult Index(string searchString)
        {
            if (string.IsNullOrEmpty(searchString)) searchString = string.Empty;
            var titles = _db.Titles.Where(t => t.TitleName.Contains(searchString)).ToList();
            //var viewModel = titles.Select(t => GetViewModel(t)).ToList();

            return View(titles);
        }
       
        public ActionResult Details(int? Id = null)
        {
            if (Id != null)
            {
                var title = _db.Titles.Single(t => t.TitleId == Id);

                return View(GetViewModel(title));
            }
            ModelState.AddModelError("Error", "Please select the movie from movie list.");
            return View();
        }

        private MoviesViewModel GetViewModel(Title title)
        {

            var _genres = _db.TitleGenres
                .Where(tg => tg.TitleId == title.TitleId)
                .Join(_db.Genres, tg => tg.GenreId, g => g.Id, (tg, g) => g).ToList();

            var _participants = _db.TitleParticipants
                .Where(tp => tp.TitleId == title.TitleId)
                .Join(_db.Participants, tp => tp.ParticipantId, p => p.Id, (tp, p) => new ParticipantViewModel
                {
                    Name = p.Name,
                    ParticipantType = p.ParticipantType,
                    RoleType = tp.RoleType
                }).ToList();

            return new MoviesViewModel
            {
                TitleId = title.TitleId,
                TitleName = title.TitleName,
                ReleaseYear = title.ReleaseYear,
                //TitleTypeId = title.TitleTypeId,
                //TitleTypeDesc = "Movie Name",
                Awards = _db.Awards.Where(a => a.TitleId == title.TitleId).ToList(),
                OtherNames = _db.OtherNames.Where(ons => ons.TitleId == title.TitleId).ToList(),
                StoryLines = _db.StoryLines.Where(ons => ons.TitleId == title.TitleId).ToList(),
                Genres = _genres,
                Participants = _participants
            };


        }
    }
}

TunerMovie/TunerMovie/Views/Movie/Details.cshtml
@model TunerMovie.Models.MoviesViewModel
@{
    ViewBag.Title = "Details";
}

<h2>Movie Details</h2>
<script src="http://code.jquery.com/jquery-1.8.2.js" type="text/javascript"></script>
@Html.ValidationMessage("Error")
@if (Model != null)
{
    <div>
        <div style="width: 100%;">
            <p>
                Title : @Html.DisplayFor(model => model.TitleName)
            </p>
        </div>
        <div>
            @Html.ActionLink("Back to movie list", "Index", "Movie")
        </div>
        <div>
            <h2>Story Lines:</h2>
            <table>
                <tr>
                    <th>
                        Story Line
                    </th>
                    <th>
                        Language
                    </th>

                    <th>
                        Type
                    </th>

                </tr>
                @foreach (var item in Model.StoryLines)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Language)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Type)
                        </td>
                    </tr>
                }
            </table>
        </div>

        <div>
            <h2>
                Genre:
            </h2>

            <table>
                <tr><th colspan=@Model.Genres.Count>Genre Type</th></tr>
                <tr>
                    @foreach (var item in Model.Genres)
                    {
                        <td>
                            @Html.DisplayFor(model => item.Name)
                        </td>
                    }
                </tr>
            </table>


        </div>

        <div>
            <h2>
                Other Names:
            </h2>

            <table>
                <tr>
                    <th>
                        Title
                    </th>
                    <th>
                        Language
                    </th>
                    <th>
                        Type
                    </th>

                </tr>
                @foreach (var item in Model.OtherNames)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TitleName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TitleNameLanguage)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TitleNameType)
                        </td>
                    </tr>
                }
            </table>


        </div>
        <div>
            <h2>
                Award:
            </h2>

            <table>
                <tr>
                    <th>
                        Award
                    </th>
                    <th>
                        Award Company
                    </th>
                    <th>
                        Award Won
                    </th>
                    <th>
                        Award Year
                    </th>
                </tr>
                @foreach (var item in Model.Awards)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Award1)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AwardCompany)
                        </td>
                        @if (item.AwardWon == true)
                        {
                            <td>
                                Yes
                            </td>
                        }
                        else
                        {
                            <td>
                                No
                            </td>
                        }
                        <td>
                            @Html.DisplayFor(modelItem => item.AwardYear)
                        </td>
                    </tr>
                }
            </table>


        </div>
        <div>
            <h2>
                Participants:
            </h2>

            <table>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Role
                    </th>
                    <th>
                        Type
                    </th>

                </tr>
                @foreach (var item in Model.Participants)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RoleType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ParticipantType)
                        </td>
                    </tr>
                }
            </table>


        </div>
    </div>
}

TunerMovie/TunerMovie/Views/Movie/Index.cshtml
@model IEnumerable<TunerMovie.Models.MoviesViewModel>
@{
    ViewBag.Title = "Index";
}

<h2>Movie List</h2>

<script src="http://code.jquery.com/jquery-1.8.2.js" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        $('#btnClear').click(function () {
            $('input[type=text]').each(function () {
                $(this).val('');
            })
        })
        $('#btnclr').click(function () {
            $('#SearchString').val('');
        })
    })
</script>
<div style="width:100%">
    @using (Html.BeginForm("Index", "Movie", FormMethod.Get))
    {
        <table >
            <tr>
                <td>Title: @Html.TextBox("SearchString")
                <td />
                <td><input type="submit" value="Search" /></td>
                <td><input type="button" name="btnclr" id="btnclr" value="Clear" /></td>
            </tr>
        </table>
    }
</div>
<br/>
<div>
    <table>
        <tr>
            <th>
                Title Name
            </th>

            <th>
               Release Year
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.TitleName, "Details", new { Id = item.TitleId })
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.ReleaseYear)
                </td>
            </tr>
        }

    </table>
</div>
<br />